### PR TITLE
Local coordinate system support 

### PR DESCRIPTION
**Pull request by mohammadamin46bd**
For Local coordinate system support :
* Passing projection as props to MapPlugin.
* Get map configuration from config.json  by using  ConfigUtils functionality.

### CODE REVIEW

**Comment by manisandro** [comment]
Is there a reason for passing the projections via map config instead of using the existing functionality of configuring the projection with the theme (i.e. [1])?

[1] https://github.com/qgis/qwc2-demo-app/blob/master/themesConfig.json#L18

**Comment by mohammadamin46bd** [comment]
Ok this functionality is already available and not needed to pass projection.

**Review by mohammadamin46bd — COMMENTED** [review]
Remove passing projction

**Comment by mohammadamin46bd** [comment]
Closing this PR.

**Pull request closed without merging**
