### PR TITLE
Add support for Swedish translations

### PR DESCRIPTION
**Pull request by igorti**

### CODE REVIEW

**Comment by manisandro** [comment]
In theory it should be sufficient to add the locale to the application in https://github.com/qgis/qwc2-demo-app/blob/master/js/appConfig.js

**Comment by igorti** [comment]
Yes, I did that as well, but it doesn't seem to be enough - `react-intl` throws tons of errors and can't find translations.

**Comment by manisandro** [comment]
Oh, that sucks, the goal would be that users are able to add translations without digging into the MapStore2 code. I'll investigate this tomorrow.

**Comment by manisandro** [comment]
Fixed in https://github.com/sourcepole/MapStore2/commit/99a9e0b83d17955417917a3e09e0fcb83b4ce5e1

**Comment by manisandro** [comment]
And https://github.com/qgis/qwc2-demo-app/commit/14a6377e78f1f47e67008ec83f84c244f6dbb90a

**Comment by igorti** [comment]
Awesome, thanks!

**Pull request closed without merging**
